### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by SzotsGabor** [TheBlackPlague/StockNemo#36]
Please include version number in exe name and UCI id.

Gabor Szots
CCRL

**Comment by TheBlackPlague** [comment]
Hello.

I apologize for it not being there already. My goal was to make the release system as similar to Stockfish's, but seems I missed a key part.

The version number will be present in all future executables.

**Comment by TheBlackPlague** [comment]
> Hi Shaheryar,
> 
> I still don't see the version number in the exe name. Also, if possible, could it also appear in the engine id name (after the uci command has been issued)?

**Comment by TheBlackPlague** [comment]
> Hi Shaheryar,
> 
> I still don't see the version number in the exe name. Also, if possible, could it also appear in the engine id name (after the uci command has been issued)?

I thought it just needed to be in the executable name. It is on all releases now.

**Comment by SzotsGabor** [comment]
Thanks, now it's really there (after opening the zip, that is).
