### ISSUE TITLE
Not working with some Cutechess binaries.

### ISSUE THREAD

**Issue by nickxadrez** [TheBlackPlague/StockNemo#39]
Hi!

What is needed to run the StockNemo engine?

My PC (Windows) supports AVX, AVX2, BMI2, POP, SS3,SS4, but unfortunately none of the versions released worked here.

How should I proceed?

**Comment by TheBlackPlague** [comment]
Hello.

StockNemo doesn't specifically require either of those. There's built in software fallbacks if you don't have POPCOUNT or BMI2. 

May I ask whether you've tried the `win-x64` / `win-x86` releases?

**Comment by TheBlackPlague** [comment]
There's more information needed regarding this issue. Please kindly respond. @nickxadrez

**Comment by rwbc** [comment]
I guess he failed because of missing info on the necessary cmd flag (for some GUIs) `--uci=True`
You should add it to the readme as suggested. A lot of people use e.g. CuteChess nowadays ;-)

OTH you are right of course, the issue misses a precise description.
The meaning of '_none ... worked here_' is void.

Guenther

**Comment by TheBlackPlague** [comment]
@rwbc Nowadays, the `--uci=True` flag isn't necessary unless you're using Cutechess CLI. On my Win11 PC, the GUI picks up StockNemo without the `--uci=True` flag. :)

Many other GUIs are also no longer requiring it, however, with cutechess-cli, it won't work without the `--uci=True` flag for some reason. I'll look into fixing that too soon.

**Comment by TheBlackPlague** [comment]
This issue is closed now as no response was given to explain the underlying problem. I hope you were able to sort it out, and if not, feel free to create another issue with proper information about the problem so we can debug it.

Thank you for using StockNemo.

**Comment by rwbc** [comment]
> @rwbc Nowadays, the `--uci=True` flag isn't necessary unless you're using Cutechess CLI. On my Win11 PC, the GUI picks up StockNemo without the `--uci=True` flag. :)
> 
> Many other GUIs are also no longer requiring it, however, with cutechess-cli, it won't work without the `--uci=True` flag for some reason. I'll look into fixing that too soon.

I use the CuteChess**GUI** mostly nowadays and quite some people too.
Here that flag is needed too.

**Comment by TheBlackPlague** [comment]
@rwbc Are y

**Comment by rwbc** [comment]
> @rwbc Are you using the latest Cutechess?
> 
> I believe older versions may have issues, but I've tested it on the latest, and 3.0.0.2 works fine without the `--uci=True` flag.

Oops, you are right I just tried the latest version and it does work w/o that flag now!
Sorry for the missinformation.

**Comment by TheBlackPlague** [comment]
@rwbc That's expected. Previous versions of StockNemo required the `--uci=True` flag. The latest version will not.

This change is specced in #35. Since this PR was merged only recently, it will only apply to **StockNemo versions >= 3.0.0.2**.
