### ISSUE TITLE
help: support for android

### ISSUE THREAD

**Issue by pavanjoshi914** [TheBlackPlague/StockNemo#95]
Firstly apprectiations to all the developers of stockNemo for this awesome project.

I was researching since a quite long time for a chess engine which can be integrated in Unity for Android.

As usual stockfish is great but can't be used for android unless it is a shared library.  and unfortunately it is not.

Do StockNemo provides support for Android? if yes, how i can use it in my unity C# project which will be built for android platforms.

any starting guide will be great for me

**Comment by TheBlackPlague** [comment]
Apologies for the late response. 

StockNemo uses `.NET Core 6.0`, which Unity doesn't directly support. If you can link the library in somehow, then a simple compilation of the library and usage of the board with the GUI of your making will work.
